//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJobMarket.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiJobMarket.Resources.UserApiResource", typeof(UserApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        internal static string APPLICATION_STATUS_ACTIVE {
            get {
                return ResourceManager.GetString("APPLICATION_STATUS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string APPLICATION_STATUS_CANCEL {
            get {
                return ResourceManager.GetString("APPLICATION_STATUS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string APPLICATION_STATUS_IGNORE {
            get {
                return ResourceManager.GetString("APPLICATION_STATUS_IGNORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the interview.
        /// </summary>
        internal static string APPLICATION_STATUS_INTERVIEW {
            get {
                return ResourceManager.GetString("APPLICATION_STATUS_INTERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate successfully.
        /// </summary>
        internal static string COMMON_AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is changed successfully.
        /// </summary>
        internal static string COMMON_CHANGEPWD_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_CHANGEPWD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password doesn&apos;t match. Type again.
        /// </summary>
        internal static string COMMON_ERROR_CONFIRMPWD_INCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_CONFIRMPWD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email could not be null.
        /// </summary>
        internal static string COMMON_ERROR_EMAIL_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_EMAIL_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your HashingData is incorrect.
        /// </summary>
        internal static string COMMON_ERROR_HASH_INCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_HASH_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash data could not be null.
        /// </summary>
        internal static string COMMON_ERROR_HASH_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_HASH_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account hasn&apos;t been activated.
        /// </summary>
        internal static string COMMON_ERROR_INACTIVE_ACCOUNT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_INACTIVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data could not be null.
        /// </summary>
        internal static string COMMON_ERROR_INPUT_DATA_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_INPUT_DATA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field could not be less than 6 characters.
        /// </summary>
        internal static string COMMON_ERROR_LESS_6_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LESS_6_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page index must between 1-50.
        /// </summary>
        internal static string COMMON_ERROR_LIMIT_PAGE_INDEX {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LIMIT_PAGE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page size must between 1-50.
        /// </summary>
        internal static string COMMON_ERROR_LIMIT_PAGE_SIZE {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LIMIT_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        internal static string COMMON_ERROR_NULL_VALUE {
            get {
                return ResourceManager.GetString("COMMON_ERROR_NULL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid integer Number.
        /// </summary>
        internal static string COMMON_ERROR_NUMBER_INT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_NUMBER_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password matches with the old password.
        /// </summary>
        internal static string COMMON_ERROR_OLDPWD_EQUAL_NEWPWD {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD_EQUAL_NEWPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password 1 is not correct.
        /// </summary>
        internal static string COMMON_ERROR_OLDPWD1_NOTCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD1_NOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password 2 is not correct.
        /// </summary>
        internal static string COMMON_ERROR_OLDPWD2_NOTCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD2_NOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPAction could not be null.
        /// </summary>
        internal static string COMMON_ERROR_OTPACTION_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPACTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPCode could not be null.
        /// </summary>
        internal static string COMMON_ERROR_OTPCODE_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPCODE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPType is ivalid.
        /// </summary>
        internal static string COMMON_ERROR_OTPTYPE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPType  could not be null.
        /// </summary>
        internal static string COMMON_ERROR_OTPTYPE_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPTYPE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field could not be more than 1000 characters.
        /// </summary>
        internal static string COMMON_ERROR_OVER_1000_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OVER_1000_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field could not be more than 50 characters.
        /// </summary>
        internal static string COMMON_ERROR_OVER_50_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OVER_50_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password could not be null.
        /// </summary>
        internal static string COMMON_ERROR_PASSWORD_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone is invalid.
        /// </summary>
        internal static string COMMON_ERROR_PHONE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone could not be null.
        /// </summary>
        internal static string COMMON_ERROR_PHONENUMBER_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PHONENUMBER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found post action.
        /// </summary>
        internal static string COMMON_ERROR_POST_ACTION_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_POST_ACTION_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PwdType is invalid. Correct value are: &apos;level1&apos; or &apos;level2&apos;.
        /// </summary>
        internal static string COMMON_ERROR_PWDTYPE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PWDTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordType could not be null.
        /// </summary>
        internal static string COMMON_ERROR_PWDTYPE_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PWDTYPE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recover password method is invalid.
        /// </summary>
        internal static string COMMON_ERROR_RECOVERPWD_METHOD_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_RECOVERPWD_METHOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is busy now. Please try again later..
        /// </summary>
        internal static string COMMON_ERROR_SYSTEM {
            get {
                return ResourceManager.GetString("COMMON_ERROR_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Time is invalid.
        /// </summary>
        internal static string COMMON_ERROR_TIME_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time could not be null.
        /// </summary>
        internal static string COMMON_ERROR_TIME_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TIME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your token is invalid.
        /// </summary>
        internal static string COMMON_ERROR_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenKey could not be null.
        /// </summary>
        internal static string COMMON_ERROR_TOKEN_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TOKEN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occurred when trying to upload files.
        /// </summary>
        internal static string COMMON_ERROR_UPLOAD_FILES {
            get {
                return ResourceManager.GetString("COMMON_ERROR_UPLOAD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId could not be null.
        /// </summary>
        internal static string COMMON_ERROR_USERID_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERID_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username could not be null.
        /// </summary>
        internal static string COMMON_ERROR_USERNAME_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERNAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired. Please sign in and try again.
        /// </summary>
        internal static string COMMON_ERROR_USERTOKEN_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERTOKEN_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The info was not found.
        /// </summary>
        internal static string COMMON_INFO_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_INFO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Api] Your OTP code is {0}.
        /// </summary>
        internal static string COMMON_OTPCODE_FORMAT {
            get {
                return ResourceManager.GetString("COMMON_OTPCODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string COMMON_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password2 has been changed successfully.
        /// </summary>
        internal static string COMMON_SUCCESS_CHANGEPWD2 {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_CHANGEPWD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new OTP code has sent to your phone [{0}]. Please verify this code..
        /// </summary>
        internal static string COMMON_SUCCESS_OTPCODE_SENT {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_OTPCODE_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName existed.
        /// </summary>
        internal static string COMMON_USERNAME_EXISTED {
            get {
                return ResourceManager.GetString("COMMON_USERNAME_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName not exists.
        /// </summary>
        internal static string COMMON_USERNAME_NOT_EXISTED {
            get {
                return ResourceManager.GetString("COMMON_USERNAME_NOT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        internal static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when connect to server.
        /// </summary>
        internal static string ERROR_E000101 {
            get {
                return ResourceManager.GetString("ERROR_E000101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string ERROR_E000102 {
            get {
                return ResourceManager.GetString("ERROR_E000102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token invalid.
        /// </summary>
        internal static string ERROR_E000103 {
            get {
                return ResourceManager.GetString("ERROR_E000103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission.
        /// </summary>
        internal static string ERROR_E000104 {
            get {
                return ResourceManager.GetString("ERROR_E000104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string ERROR_E000105 {
            get {
                return ResourceManager.GetString("ERROR_E000105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully.
        /// </summary>
        internal static string ERROR_E000106 {
            get {
                return ResourceManager.GetString("ERROR_E000106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        internal static string ERROR_E000107 {
            get {
                return ResourceManager.GetString("ERROR_E000107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key does not exist.
        /// </summary>
        internal static string ERROR_E000108 {
            get {
                return ResourceManager.GetString("ERROR_E000108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data type or range.
        /// </summary>
        internal static string ERROR_E000109 {
            get {
                return ResourceManager.GetString("ERROR_E000109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of searching conditions.
        /// </summary>
        internal static string ERROR_E000110 {
            get {
                return ResourceManager.GetString("ERROR_E000110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of data fields.
        /// </summary>
        internal static string ERROR_E000111 {
            get {
                return ResourceManager.GetString("ERROR_E000111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data does not exists.
        /// </summary>
        internal static string ERROR_E000112 {
            get {
                return ResourceManager.GetString("ERROR_E000112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password.
        /// </summary>
        internal static string ERROR_E010101 {
            get {
                return ResourceManager.GetString("ERROR_E010101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not active.
        /// </summary>
        internal static string ERROR_E010102 {
            get {
                return ResourceManager.GetString("ERROR_E010102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have admin pemission for login.
        /// </summary>
        internal static string ERROR_E010103 {
            get {
                return ResourceManager.GetString("ERROR_E010103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have permission to access email of Facebook account.
        /// </summary>
        internal static string ERROR_E010104 {
            get {
                return ResourceManager.GetString("ERROR_E010104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have permission to access email of Google account.
        /// </summary>
        internal static string ERROR_E010105 {
            get {
                return ResourceManager.GetString("ERROR_E010105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format.
        /// </summary>
        internal static string ERROR_E010201 {
            get {
                return ResourceManager.GetString("ERROR_E010201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already existed.
        /// </summary>
        internal static string ERROR_E010202 {
            get {
                return ResourceManager.GetString("ERROR_E010202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send activation email.
        /// </summary>
        internal static string ERROR_E010203 {
            get {
                return ResourceManager.GetString("ERROR_E010203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect authentication code please check the link.
        /// </summary>
        internal static string ERROR_E010301 {
            get {
                return ResourceManager.GetString("ERROR_E010301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already activated.
        /// </summary>
        internal static string ERROR_E010302 {
            get {
                return ResourceManager.GetString("ERROR_E010302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully activated. Please log in again on the app.
        /// </summary>
        internal static string ERROR_E010303 {
            get {
                return ResourceManager.GetString("ERROR_E010303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already changed your password.
        /// </summary>
        internal static string ERROR_E010401 {
            get {
                return ResourceManager.GetString("ERROR_E010401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect authentication code please check the link.
        /// </summary>
        internal static string ERROR_E010402 {
            get {
                return ResourceManager.GetString("ERROR_E010402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string ERROR_E010403 {
            get {
                return ResourceManager.GetString("ERROR_E010403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is not exist.
        /// </summary>
        internal static string ERROR_E010501 {
            get {
                return ResourceManager.GetString("ERROR_E010501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has not been activated yet.
        /// </summary>
        internal static string ERROR_E010502 {
            get {
                return ResourceManager.GetString("ERROR_E010502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending email.
        /// </summary>
        internal static string ERROR_E010503 {
            get {
                return ResourceManager.GetString("ERROR_E010503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was sent successfully please check your mailbox again.
        /// </summary>
        internal static string ERROR_E010504 {
            get {
                return ResourceManager.GetString("ERROR_E010504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is incorrect, please check again.
        /// </summary>
        internal static string ERROR_E010601 {
            get {
                return ResourceManager.GetString("ERROR_E010601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication was sent, please check your mailbox.
        /// </summary>
        internal static string ERROR_E010602 {
            get {
                return ResourceManager.GetString("ERROR_E010602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description already existed.
        /// </summary>
        internal static string ERROR_E020101 {
            get {
                return ResourceManager.GetString("ERROR_E020101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This CV is not exists.
        /// </summary>
        internal static string ERROR_E030101 {
            get {
                return ResourceManager.GetString("ERROR_E030101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code_id already existed.
        /// </summary>
        internal static string ERROR_E030102 {
            get {
                return ResourceManager.GetString("ERROR_E030102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code_id has been saved.
        /// </summary>
        internal static string ERROR_E030103 {
            get {
                return ResourceManager.GetString("ERROR_E030103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code_id is not exists.
        /// </summary>
        internal static string ERROR_E030104 {
            get {
                return ResourceManager.GetString("ERROR_E030104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file size does not exceed 50MB.
        /// </summary>
        internal static string ERROR_E030105 {
            get {
                return ResourceManager.GetString("ERROR_E030105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user_id or work_status.
        /// </summary>
        internal static string ERROR_E040101 {
            get {
                return ResourceManager.GetString("ERROR_E040101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job is not exists.
        /// </summary>
        internal static string ERROR_E050101 {
            get {
                return ResourceManager.GetString("ERROR_E050101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job already applied.
        /// </summary>
        internal static string ERROR_E050102 {
            get {
                return ResourceManager.GetString("ERROR_E050102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job already saved.
        /// </summary>
        internal static string ERROR_E050103 {
            get {
                return ResourceManager.GetString("ERROR_E050103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company is not exists.
        /// </summary>
        internal static string ERROR_E060101 {
            get {
                return ResourceManager.GetString("ERROR_E060101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career sheet not found.
        /// </summary>
        internal static string ERROR_E070101 {
            get {
                return ResourceManager.GetString("ERROR_E070101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string ERROR_FIELD_NOT_NULL_REQUIRED {
            get {
                return ResourceManager.GetString("ERROR_FIELD_NOT_NULL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only send up to {0} invitations each job.
        /// </summary>
        internal static string ERROR_INVITATION_LIMIT_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVITATION_LIMIT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password2 is incorrect.
        /// </summary>
        internal static string ERROR_PWD2_INCORRECT {
            get {
                return ResourceManager.GetString("ERROR_PWD2_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum video length could not be large than {0} MB.
        /// </summary>
        internal static string ERROR_VIDEO_UPLOAD_LIMIT_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_VIDEO_UPLOAD_LIMIT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string INVITATION_STATUS_ACCEPTED {
            get {
                return ResourceManager.GetString("INVITATION_STATUS_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awating.
        /// </summary>
        internal static string INVITATION_STATUS_AWAITING {
            get {
                return ResourceManager.GetString("INVITATION_STATUS_AWAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        internal static string INVITATION_STATUS_IGNORED {
            get {
                return ResourceManager.GetString("INVITATION_STATUS_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string JOB_STATUS_CANCELED {
            get {
                return ResourceManager.GetString("JOB_STATUS_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string JOB_STATUS_CLOSED {
            get {
                return ResourceManager.GetString("JOB_STATUS_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string JOB_STATUS_DRAFT {
            get {
                return ResourceManager.GetString("JOB_STATUS_DRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string JOB_STATUS_PUBLISHED {
            get {
                return ResourceManager.GetString("JOB_STATUS_PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string JOB_STATUS_SAVED {
            get {
                return ResourceManager.GetString("JOB_STATUS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username or Password are incorrect.
        /// </summary>
        internal static string LOGIN_ERROR_INFO_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_INFO_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Time is invalid.
        /// </summary>
        internal static string LOGIN_ERROR_TIME_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully.
        /// </summary>
        internal static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on post.
        /// </summary>
        internal static string NOTIF_COMMENT {
            get {
                return ResourceManager.GetString("NOTIF_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liked your post.
        /// </summary>
        internal static string NOTIF_LIKE {
            get {
                return ResourceManager.GetString("NOTIF_LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTPCode has been expired.
        /// </summary>
        internal static string OTP_ERROR_OTPCODE_EXPIRED {
            get {
                return ResourceManager.GetString("OTP_ERROR_OTPCODE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPCode is not exists or already used.
        /// </summary>
        internal static string OTP_ERROR_OTPCODE_NOTEXISTS_ORUSED {
            get {
                return ResourceManager.GetString("OTP_ERROR_OTPCODE_NOTEXISTS_ORUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new OTP successfully.
        /// </summary>
        internal static string OTP_SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("OTP_SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPCode was verified successfully.
        /// </summary>
        internal static string OTP_SUCCESS_VERIFY {
            get {
                return ResourceManager.GetString("OTP_SUCCESS_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal TokenKey error.
        /// </summary>
        internal static string REFRESHTOKEN_ERROR {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal token key successfully.
        /// </summary>
        internal static string REFRESHTOKEN_SUCCESS {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birhday format is not correct. The correct format is: dd/mm/yyyy.
        /// </summary>
        internal static string REGISTER_ERROR_BIRTHDAY_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_BIRTHDAY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used.
        /// </summary>
        internal static string REGISTER_ERROR_EMAIL_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_EMAIL_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDCard already used.
        /// </summary>
        internal static string REGISTER_ERROR_IDCARD_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_IDCARD_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber already used.
        /// </summary>
        internal static string REGISTER_ERROR_PHONE_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_PHONE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName already used.
        /// </summary>
        internal static string REGISTER_ERROR_USERNAME_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_USERNAME_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register successfully.
        /// </summary>
        internal static string REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application accepted to interview successfully.
        /// </summary>
        internal static string SUCCESS_APPLICATION_ACCEPT_INTERVIEW {
            get {
                return ResourceManager.GetString("SUCCESS_APPLICATION_ACCEPT_INTERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been ignored.
        /// </summary>
        internal static string SUCCESS_APPLICATION_IGNORED {
            get {
                return ResourceManager.GetString("SUCCESS_APPLICATION_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application send CV successfully.
        /// </summary>
        internal static string SUCCESS_APPLICATION_SEND_CV {
            get {
                return ResourceManager.GetString("SUCCESS_APPLICATION_SEND_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career sheet created successfully.
        /// </summary>
        internal static string SUCCESS_CS_CREATED {
            get {
                return ResourceManager.GetString("SUCCESS_CS_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career sheet updated successfully.
        /// </summary>
        internal static string SUCCESS_CS_UPDATED {
            get {
                return ResourceManager.GetString("SUCCESS_CS_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV was created successfully.
        /// </summary>
        internal static string SUCCESS_CV_CREATED {
            get {
                return ResourceManager.GetString("SUCCESS_CV_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV was updated successfully.
        /// </summary>
        internal static string SUCCESS_CV_UPDATED {
            get {
                return ResourceManager.GetString("SUCCESS_CV_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation has been accepted.
        /// </summary>
        internal static string SUCCESS_INVITATION_ACCEPTED {
            get {
                return ResourceManager.GetString("SUCCESS_INVITATION_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation has been ignored.
        /// </summary>
        internal static string SUCCESS_INVITATION_IGNORED {
            get {
                return ResourceManager.GetString("SUCCESS_INVITATION_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job applied successfully.
        /// </summary>
        internal static string SUCCESS_JOB_APPLY {
            get {
                return ResourceManager.GetString("SUCCESS_JOB_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job cancelled successfully.
        /// </summary>
        internal static string SUCCESS_JOB_CANCEL {
            get {
                return ResourceManager.GetString("SUCCESS_JOB_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job saved successfully.
        /// </summary>
        internal static string SUCCESS_JOB_SAVE {
            get {
                return ResourceManager.GetString("SUCCESS_JOB_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password2 is correct.
        /// </summary>
        internal static string SUCCESS_PWD2_CORRECT {
            get {
                return ResourceManager.GetString("SUCCESS_PWD2_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string SUCCESS_SAVED {
            get {
                return ResourceManager.GetString("SUCCESS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info updated successfully.
        /// </summary>
        internal static string UPDATE_INFO_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_INFO_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        internal static string UPDATE_PROFILE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_SUCCESS", resourceCulture);
            }
        }
    }
}
