//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserWebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserWebResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingleSignOn.Resources.UserWebResource", typeof(UserWebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi thành công.
        /// </summary>
        public static string COMMON_CHANGEPWD_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_CHANGEPWD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng phương thức này .
        /// </summary>
        public static string COMMON_ERROR_AUTH_METHOD_SELECTED {
            get {
                return ResourceManager.GetString("COMMON_ERROR_AUTH_METHOD_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã nhập sai mã Captcha.
        /// </summary>
        public static string COMMON_ERROR_CAPTCHA_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_CAPTCHA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu chưa đúng.
        /// </summary>
        public static string COMMON_ERROR_CONFIRMPWD_INCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_CONFIRMPWD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_DATA_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_DATA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email.
        /// </summary>
        public static string COMMON_ERROR_EMAIL_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_EMAIL_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ đang bận, vui lòng thử lại sau.
        /// </summary>
        public static string COMMON_ERROR_EXTERNALSERVICE_TIMEOUT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_EXTERNALSERVICE_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi mã hóa không đúng.
        /// </summary>
        public static string COMMON_ERROR_HASH_INCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_HASH_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cung cấp chuỗi mã hóa.
        /// </summary>
        public static string COMMON_ERROR_HASH_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_HASH_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin.
        /// </summary>
        public static string COMMON_ERROR_INFO_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_INFO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ít nhất 6 ký tự.
        /// </summary>
        public static string COMMON_ERROR_LESS_6_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LESS_6_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới trùng với mật khẩu cũ.
        /// </summary>
        public static string COMMON_ERROR_OLDPWD_EQUAL_NEWPWD {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD_EQUAL_NEWPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        public static string COMMON_ERROR_OLDPWD1_NOTCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD1_NOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cấp 2 cũ không đúng.
        /// </summary>
        public static string COMMON_ERROR_OLDPWD2_NOTCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD2_NOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập không quá 1000 ký tự.
        /// </summary>
        public static string COMMON_ERROR_OVER_1000_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OVER_1000_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập không quá 50 ký tự.
        /// </summary>
        public static string COMMON_ERROR_OVER_50_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OVER_50_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu.
        /// </summary>
        public static string COMMON_ERROR_PASSWORD_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_PHONE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        public static string COMMON_ERROR_PHONENUMBER_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PHONENUMBER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức khôi phục không được để trống.
        /// </summary>
        public static string COMMON_ERROR_RECOVER_METHOD_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_RECOVER_METHOD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_TIME_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập vào thời gian.
        /// </summary>
        public static string COMMON_ERROR_TIME_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TIME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cung cấp token.
        /// </summary>
        public static string COMMON_ERROR_TOKEN_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TOKEN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id tài khoản không được để trống.
        /// </summary>
        public static string COMMON_ERROR_USERID_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERID_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên đăng nhập.
        /// </summary>
        public static string COMMON_ERROR_USERNAME_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERNAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại hoặc token không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_USERTOKEN_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERTOKEN_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bận, vui lòng thử lại sau.
        /// </summary>
        public static string COMMON_EXCEPTION_NOTIF {
            get {
                return ResourceManager.GetString("COMMON_EXCEPTION_NOTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma OTP cua ban la {0}.
        /// </summary>
        public static string COMMON_OTPCODE_FORMAT {
            get {
                return ResourceManager.GetString("COMMON_OTPCODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cấp 2 đã được thay đổi thành công.
        /// </summary>
        public static string COMMON_SUCCESS_CHANGEPWD2 {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_CHANGEPWD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã được gửi tới số điện thoại của bạn Vui lòng xác nhận.
        /// </summary>
        public static string COMMON_SUCCESS_OTPCODE_SENT {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_OTPCODE_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        public static string LOGIN_ERROR_INFO_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_INFO_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không hợp lệ.
        /// </summary>
        public static string LOGIN_ERROR_TIME_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn.
        /// </summary>
        public static string OTP_ERROR_OTPCODE_EXPIRED {
            get {
                return ResourceManager.GetString("OTP_ERROR_OTPCODE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không tồn tại hoặc đã được sử dụng.
        /// </summary>
        public static string OTP_ERROR_OTPCODE_NOTEXISTS_ORUSED {
            get {
                return ResourceManager.GetString("OTP_ERROR_OTPCODE_NOTEXISTS_ORUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mã OTP thành công.
        /// </summary>
        public static string OTP_SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("OTP_SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTTP đã được xác nhận thành công.
        /// </summary>
        public static string OTP_SUCCESS_VERIFY {
            get {
                return ResourceManager.GetString("OTP_SUCCESS_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không hợp lệ. Định dạng: dd/mm/yyyy.
        /// </summary>
        public static string REGISTER_ERROR_BIRTHDAY_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_BIRTHDAY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_EMAIL_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_EMAIL_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng minh thư đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_IDCARD_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_IDCARD_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_PHONE_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_PHONE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_USERNAME_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_USERNAME_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        public static string REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã được kích hoạt thành công.
        /// </summary>
        public static string SUCCESS_ACCOUNT_ACTIVED {
            get {
                return ResourceManager.GetString("SUCCESS_ACCOUNT_ACTIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string TEXT_ACCOUNT {
            get {
                return ResourceManager.GetString("TEXT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tài khoản?.
        /// </summary>
        public static string TEXT_ALREADY_HAVE_ACC {
            get {
                return ResourceManager.GetString("TEXT_ALREADY_HAVE_ACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string TEXT_CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã Captcha.
        /// </summary>
        public static string TEXT_CAPTCHA_NULL {
            get {
                return ResourceManager.GetString("TEXT_CAPTCHA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        public static string TEXT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("TEXT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bấm.
        /// </summary>
        public static string TEXT_CLICK {
            get {
                return ResourceManager.GetString("TEXT_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string TEXT_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("TEXT_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cắt ảnh.
        /// </summary>
        public static string TEXT_CROP_AVATAR_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_CROP_AVATAR_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản?.
        /// </summary>
        public static string TEXT_DONT_HAVE_ACC {
            get {
                return ResourceManager.GetString("TEXT_DONT_HAVE_ACC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TEXT_EMAIL {
            get {
                return ResourceManager.GetString("TEXT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        public static string TEXT_HELP {
            get {
                return ResourceManager.GetString("TEXT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string TEXT_LANGUAGE {
            get {
                return ResourceManager.GetString("TEXT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string TEXT_LOGIN {
            get {
                return ResourceManager.GetString("TEXT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email, tên đăng nhập, số điện thoại.
        /// </summary>
        public static string TEXT_LOGIN_ACCOUNT {
            get {
                return ResourceManager.GetString("TEXT_LOGIN_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string TEXT_LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước tối đa.
        /// </summary>
        public static string TEXT_MAXIMUM_SIZE {
            get {
                return ResourceManager.GetString("TEXT_MAXIMUM_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string TEXT_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("TEXT_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string TEXT_PASSWORD {
            get {
                return ResourceManager.GetString("TEXT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string TEXT_PHONE {
            get {
                return ResourceManager.GetString("TEXT_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đã đọc và đồng ý với.
        /// </summary>
        public static string TEXT_READ_ALLOW {
            get {
                return ResourceManager.GetString("TEXT_READ_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        public static string TEXT_REFRESH_CAPTCHA_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_REFRESH_CAPTCHA_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã Captcha ở trên.
        /// </summary>
        public static string TEXT_REFRESH_CAPTCHA_DESC {
            get {
                return ResourceManager.GetString("TEXT_REFRESH_CAPTCHA_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string TEXT_REGISTER {
            get {
                return ResourceManager.GetString("TEXT_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duy trì đăng nhập.
        /// </summary>
        public static string TEXT_REMEMBER_ME {
            get {
                return ResourceManager.GetString("TEXT_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string TEXT_SUBMIT_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_SUBMIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các điều khoản và điều kiện chung.
        /// </summary>
        public static string TEXT_TERM_CONDITION {
            get {
                return ResourceManager.GetString("TEXT_TERM_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để.
        /// </summary>
        public static string TEXT_TO {
            get {
                return ResourceManager.GetString("TEXT_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực email.
        /// </summary>
        public static string TEXT_VERIFY_EMAIL {
            get {
                return ResourceManager.GetString("TEXT_VERIFY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hồ sơ thành công.
        /// </summary>
        public static string UPDATE_PROFILE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_SUCCESS", resourceCulture);
            }
        }
    }
}
