//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingleSignOn.Resources.UserApiResource", typeof(UserApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực thành công.
        /// </summary>
        public static string COMMON_AUTH_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_AUTH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công.
        /// </summary>
        public static string COMMON_CHANGEPWD_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_CHANGEPWD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản đăng ký bằng địa chỉ email này.
        /// </summary>
        public static string COMMON_ERROR_ACCOUNT_BY_EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_ACCOUNT_BY_EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã bị khóa.
        /// </summary>
        public static string COMMON_ERROR_BLOCKED_ACCOUNT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_BLOCKED_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không khớp với mật khẩu.
        /// </summary>
        public static string COMMON_ERROR_CONFIRMPWD_INCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_CONFIRMPWD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        public static string COMMON_ERROR_EMAIL_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_EMAIL_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi mã hóa không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_HASH_INCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_HASH_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi mã hóa không được để trống.
        /// </summary>
        public static string COMMON_ERROR_HASH_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_HASH_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chưa được kích hoạt.
        /// </summary>
        public static string COMMON_ERROR_INACTIVE_ACCOUNT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_INACTIVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào chưa hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_INPUT_DATA_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_INPUT_DATA_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ít nhất 6 ký tự.
        /// </summary>
        public static string COMMON_ERROR_LESS_6_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LESS_6_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang phải nằm trong khoảng 1-50.
        /// </summary>
        public static string COMMON_ERROR_LIMIT_PAGE_INDEX {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LIMIT_PAGE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bản ghi phải nằm trong khoảng 1-50.
        /// </summary>
        public static string COMMON_ERROR_LIMIT_PAGE_SIZE {
            get {
                return ResourceManager.GetString("COMMON_ERROR_LIMIT_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đang trống.
        /// </summary>
        public static string COMMON_ERROR_NULL_VALUE {
            get {
                return ResourceManager.GetString("COMMON_ERROR_NULL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập vào số nguyên hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_NUMBER_INT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_NUMBER_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới trùng với mật khẩu cũ.
        /// </summary>
        public static string COMMON_ERROR_OLDPWD_EQUAL_NEWPWD {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD_EQUAL_NEWPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        public static string COMMON_ERROR_OLDPWD1_NOTCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD1_NOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cấp 2 không đúng.
        /// </summary>
        public static string COMMON_ERROR_OLDPWD2_NOTCORRECT {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OLDPWD2_NOTCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPAction không được để trống.
        /// </summary>
        public static string COMMON_ERROR_OTPACTION_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPACTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPCode không được để trống.
        /// </summary>
        public static string COMMON_ERROR_OTPCODE_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPCODE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPType không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_OTPTYPE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTPType  không được để trống.
        /// </summary>
        public static string COMMON_ERROR_OTPTYPE_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OTPTYPE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập không quá 1000 ký tự.
        /// </summary>
        public static string COMMON_ERROR_OVER_1000_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OVER_1000_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập không quá 50 ký tự.
        /// </summary>
        public static string COMMON_ERROR_OVER_50_CHARACTERS {
            get {
                return ResourceManager.GetString("COMMON_ERROR_OVER_50_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        public static string COMMON_ERROR_PASSWORD_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_PHONE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được để trống.
        /// </summary>
        public static string COMMON_ERROR_PHONENUMBER_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PHONENUMBER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tương tác không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_POST_ACTION_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_POST_ACTION_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordType không hợp lệ. Giá trị hợp lệ: &apos;level1&apos; hoặc &apos;level2&apos;.
        /// </summary>
        public static string COMMON_ERROR_PWDTYPE_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PWDTYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordType không được để trống.
        /// </summary>
        public static string COMMON_ERROR_PWDTYPE_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_PWDTYPE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức khôi phục mật khẩu không đúng.
        /// </summary>
        public static string COMMON_ERROR_RECOVERPWD_METHOD_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_RECOVERPWD_METHOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bận, vui lòng thử lại sau..
        /// </summary>
        public static string COMMON_ERROR_SYSTEM {
            get {
                return ResourceManager.GetString("COMMON_ERROR_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian của bạn không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_TIME_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không được để trống.
        /// </summary>
        public static string COMMON_ERROR_TIME_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TIME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ.
        /// </summary>
        public static string COMMON_ERROR_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenKey không được để trống.
        /// </summary>
        public static string COMMON_ERROR_TOKEN_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_TOKEN_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra trong khi tải ảnh lên.
        /// </summary>
        public static string COMMON_ERROR_UPLOAD_FILES {
            get {
                return ResourceManager.GetString("COMMON_ERROR_UPLOAD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id người dùng không được để trống.
        /// </summary>
        public static string COMMON_ERROR_USERID_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERID_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được để trống.
        /// </summary>
        public static string COMMON_ERROR_USERNAME_NULL {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERNAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên làm việc đã hết hạn. Vui lòng đăng đăng nhập và thử lại.
        /// </summary>
        public static string COMMON_ERROR_USERTOKEN_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_ERROR_USERTOKEN_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin không tồn tại.
        /// </summary>
        public static string COMMON_INFO_NOTFOUND {
            get {
                return ResourceManager.GetString("COMMON_INFO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Halo] Ma OTP cua ban la {0}.
        /// </summary>
        public static string COMMON_OTPCODE_FORMAT {
            get {
                return ResourceManager.GetString("COMMON_OTPCODE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string COMMON_SUCCESS {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu  cấp 2 thành công.
        /// </summary>
        public static string COMMON_SUCCESS_CHANGEPWD2 {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_CHANGEPWD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một mã OTP đã được gửi đến số điện thoại [{0}] của bạn. Vui lòng xác nhận.
        /// </summary>
        public static string COMMON_SUCCESS_OTPCODE_SENT {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_OTPCODE_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng và token hợp lệ.
        /// </summary>
        public static string COMMON_SUCCESS_TOKEN_VALID {
            get {
                return ResourceManager.GetString("COMMON_SUCCESS_TOKEN_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được sử dụng.
        /// </summary>
        public static string COMMON_USERNAME_EXISTED {
            get {
                return ResourceManager.GetString("COMMON_USERNAME_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        public static string COMMON_USERNAME_NOT_EXISTED {
            get {
                return ResourceManager.GetString("COMMON_USERNAME_NOT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cấp 2 không đúng.
        /// </summary>
        public static string ERROR_PWD2_INCORRECT {
            get {
                return ResourceManager.GetString("ERROR_PWD2_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này đã được kích hoạt.
        /// </summary>
        public static string LB_THIS_ACCOUNT_ALREADY_ACTIVED {
            get {
                return ResourceManager.GetString("LB_THIS_ACCOUNT_ALREADY_ACTIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string LOGIN_ERROR_INFO_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_INFO_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian của bạn không hợp lệ.
        /// </summary>
        public static string LOGIN_ERROR_TIME_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_ERROR_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn.
        /// </summary>
        public static string OTP_ERROR_OTPCODE_EXPIRED {
            get {
                return ResourceManager.GetString("OTP_ERROR_OTPCODE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không tồn tại hoặc đã được sử dụng.
        /// </summary>
        public static string OTP_ERROR_OTPCODE_NOTEXISTS_ORUSED {
            get {
                return ResourceManager.GetString("OTP_ERROR_OTPCODE_NOTEXISTS_ORUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới mã OTP thành công.
        /// </summary>
        public static string OTP_SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("OTP_SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã được xác nhận thành công.
        /// </summary>
        public static string OTP_SUCCESS_VERIFY {
            get {
                return ResourceManager.GetString("OTP_SUCCESS_VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia hạn TokenKey không thành công.
        /// </summary>
        public static string REFRESHTOKEN_ERROR {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia hạn TokenKey thành công.
        /// </summary>
        public static string REFRESHTOKEN_SUCCESS {
            get {
                return ResourceManager.GetString("REFRESHTOKEN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai định dạng ngày tháng. Định dạng hợp lệ: dd/mm/yyyy.
        /// </summary>
        public static string REGISTER_ERROR_BIRTHDAY_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_BIRTHDAY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_EMAIL_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_EMAIL_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMT đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_IDCARD_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_IDCARD_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_PHONE_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_PHONE_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được sử dụng.
        /// </summary>
        public static string REGISTER_ERROR_USERNAME_USED {
            get {
                return ResourceManager.GetString("REGISTER_ERROR_USERNAME_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        public static string REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cấp 2 hợp lệ.
        /// </summary>
        public static string SUCCESS_PWD2_CORRECT {
            get {
                return ResourceManager.GetString("SUCCESS_PWD2_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hồ sơ thành công.
        /// </summary>
        public static string UPDATE_PROFILE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_SUCCESS", resourceCulture);
            }
        }
    }
}
